export const FooterLinks = [
    {
        FooterLinkContentinfo: 'Our Brands',
    },
    {
        FooterLinkContentinfo: 'Where To Buy',
    },
    {
        FooterLink: 'Sign Up for Newsletter',
        LinkHeading: 'Be the first to know',
        LinkText: 'Sign up now to get our latest',
    },
    {
        FooterPopLink: 'Charitable Partners',
    },
    {
        FooterPopLink: 'Careers',
    },
    {
        FooterPopLink: 'Out of Home',
    },
    {
        FooterLink: 'Sitemap',
        LinkHeading: 'Sitemap',
    },
    {
        FooterPopLink: 'Modern Slavery Report',
    },
    {
        FooterTextLink: 'Cookie Preferences',
        RejectButton: 'Reject All',
    },
    {
        FooterTextLink: 'Contact Us',
    },
    {
        FooterLink: 'Terms of Use',
    },
    {
        FooterLink: 'Accessibility',
        LinkHeading: 'Accessibility',
    },
    {
        FooterLink: 'Privacy Notice',
        cookiesButton: 'Accept Cookies',
        LinkHeading: 'Kellanova Consumer Privacy',
    },
]

export const kellanovaHeaderLinks = [
    {
        HeaderLink: 'Our Brands',
        HedearImg: '.kstl-feature-inset',
        HeaderRoleText: 'Brands',
        HeaderProductLink: 'Eggo Brand page',
        HeaderTextOne: 'A great tasting, warm part of',
        HeaderTextTwo: 'Our products',
        HeaderProductList: 'Kellogg\'s* Eggo* Thick & Fluffy Strawberry Delight Waffles',
        HeaderProductImg:'Eggo T&F Strawberry EN',
        HeaderProductRoleText: 'Kellogg\'s* Eggo* Thick &',
        HeaderProductTextOne: 'Mornings just got sweeter',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Kellogg\'s* Eggo* Eggoji',
        HeaderProductImg:'Eggoji EN',
        HeaderProductRoleText: 'Kellogg\'s* Eggo* Eggoji Original Waffles',
        HeaderProductTextOne: 'Express yourself in the',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Kellogg\'s* Eggo* Original Whole Grain Waffles',
        HeaderProductImg:'Wholegrain original EN',
        HeaderProductRoleText: 'Kellogg\'s* Eggo* Original Whole Grain Waffles',
        HeaderProductTextOne: 'Our Kellogg\'s* Eggo* waffles',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Kellogg\'s* Eggo* Waffles',
        HeaderProductImg:'Buttermilk waffles EN',
        HeaderProductRoleText: 'Kellogg\'s* Eggo* Waffles',
        HeaderProductTextOne: 'Wake up with this tasty',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Kellogg\'s* Eggo* Chocolatey Chip Waffles',
        HeaderProductImg:'Choc Chip EN',
        HeaderProductRoleText: 'Kellogg\'s* Eggo* Chocolatey',
        HeaderProductTextOne: 'Get a sweet start to your',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Kellogg\'s* Eggo* Waffles',
        HeaderProductImg:'Buttermilk waffles EN',
        HeaderProductRoleText: 'Kellogg\'s* Eggo* Waffles Buttermilk',
        HeaderProductTextOne: 'Wake up with this tasty',
        HeaderProductTextTwo: 'Purchase This Product Online',
        Goback: true,
    },
    {
        HeaderProductLink: 'Kelloggs Town House Brand page',
        HeaderTextOne: 'With Kellogg’s* Town House*',
        HeaderTextTwo: 'Our products',
        HeaderProductList: 'Town House* Pita Mediterranean Herb Crackers',
        HeaderProductImg:'00064100150102_C1L1_en',
        HeaderProductRoleText: 'Town House* Pita',
        HeaderProductTextOne: 'Crisp, oven-baked and made',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Town House* Flatbread Crisps Italian Herb Crackers',
        HeaderProductImg:'00064100148864_A1L1_en',
        HeaderProductRoleText: 'Town House* Flatbread Crisps',
        HeaderProductTextOne: 'Oven-baked crackers with a rustic blend of savoury spices.',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Town House* Pita Sea Salt',
        HeaderProductImg:'00064100148284_A1L1_en-',
        HeaderProductRoleText: 'Town House* Pita Sea Salt',
        HeaderProductTextOne: 'Crisp, oven-baked crackers',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Kellogg’s* Town House* Original Cracker',
        HeaderProductImg:'TH Original - EN',
        HeaderProductRoleText: 'Kellogg’s* Town House*',
        HeaderProductTextOne: 'Crisp, classic cracker on one side... perfect pretzel flavour on the other.',
        HeaderProductTextTwo: 'Purchase This Product Online',
        Goback: true,
    },
    {
        HeaderProductLink: 'Nutrigrain Brand page',
        HeaderTextOne: 'Delicious soft-baked goodness',
        HeaderTextTwo: 'Our products',
        HeaderProductList: 'Nutri-Grain* Raspberry Cereal',
        HeaderProductImg:'NG Raspberry',
        HeaderProductRoleText: 'Nutri-Grain* Mixed Berry Cereal Bars',
        HeaderProductTextOne: 'Enjoy the goodness of wheat and rolled oats paired with a perfectly mixed natural berry flavour blend. Made with 10g of whole grains per serving (37 g) and no artificial colours, Nutri-Grain* Mixed Berry bars are deliciously satisfying to the very last bite.',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Nutri-Grain* Raspberry Cereal',
        HeaderProductImg:'NG Raspberry',
        HeaderProductRoleText: 'Nutri-Grain* Raspberry Cereal Bars',
        HeaderProductTextOne: 'Enjoy the goodness of wheat and rolled oats with the taste of raspberry. Made with 10g of whole grains per serving (37 g) and no artificial colours, Nutri-Grain* Raspberry bars are perfectly satisfying with every tasty bite.',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Nutri-Grain* Strawberry',
        HeaderProductImg:'NG Strawberry',
        HeaderProductRoleText: 'Nutri-Grain* Strawberry Cereal Bars',
        HeaderProductTextOne: 'Enjoy the goodness of wheat and rolled oats paired with the taste of strawberry. Made with 10g of whole grains per serving (37 g) and no artificial colours, Nutri-Grain* Strawberry bars are the perfect fix to satisfy cravings anywhere, anytime.',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Nutri-Grain* Apple Cinnamon',
        HeaderProductImg:'NG Apple Cinnamon',
        HeaderProductRoleText: 'Nutri-Grain* Blueberry Cereal Bars',
        HeaderProductTextOne: 'Enjoy the goodness of wheat and rolled oats with the taste of blueberry. Made with 10g of whole grains per serving (37 g) and no artificial colours, Nutri-Grain* Blueberry bars deliver flavourful satisfaction anytime.',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Nutri-Grain* Strawberry',
        HeaderProductImg:'NG Strawberry',
        HeaderProductRoleText: 'Nutri-Grain* Apple Cinnamon Cereal Bars',
        HeaderProductTextOne: 'Enjoy the goodness of wheat and rolled oats with the taste of cinnamon spiced apple. Made with 10 g of whole grains per serving (37 g) and no artificial colours, Nutri-Grain* Apple Cinnamon bars are the perfect fix to satisfy cravings anywhere, anytime.',
        HeaderProductTextTwo: 'Purchase This Product Online',
        Goback: true,
    },
    {
        HeaderProductLink: 'Pop-Tarts Brand page',
        HeaderTextOne: 'Add a little fun to you',
        HeaderTextTwo: 'Our products',
        HeaderProductList: 'Pop-Tarts* Bites Mini Pastries Frosted Blueberry Flavour',
        HeaderProductImg:'PT Bites blueberry',
        HeaderProductRoleText: 'Pop-Tarts* Bites Mini Pastries Frosted Blueberry Flavour',
        HeaderProductTextOne: 'Pop-Tarts* Bites Frosted Blueberry Flavour Mini-Pastries have a beautiful golden crust, real fruit blueberry filling and topped with frosting and colourful confetti. Perfect for popping into your mouth when you crave a delicious bite!',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Pop-Tarts* Bites Mini Pastries Frosted Blueberry Flavour',
        HeaderProductImg:'PT Bites blueberry',
        HeaderProductRoleText: 'Pop-Tarts* Frosted Raspberry Toaster Pastries',
        HeaderProductTextOne: 'Toasted, frozen, or straight from the box ; add a little fun to your day with our classic, best selling Pop-Tarts Frosted Raspberry toaster pastries. A delicious golden crust, stuffed with filling made with real fruit, frosted with icing and topped with coloured sprinkles. A fun and fruity way to awaken your senses.',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Pop-Tarts* Bites Mini Pastries Frosted Cinnamon Roll',
        HeaderProductImg:'00064100148390_A1L1',
        HeaderProductRoleText: 'Pop-Tarts* Bites Mini Pastries Frosted Cinnamon Roll',
        HeaderProductTextOne: 'Pop-Tarts* Bites Frosted Cinnamon Roll Mini-Pastries come in a beautiful golden crust filled with a delicious cream cheese filling, aromatic cinnamon flavours, and topped with white frosting and crunchlets. These pastries come in bite size pieces which makes it so easy to pop into your mouth when you’re craving a sweet bite!',
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Pop-Tarts* Frosted Raspberry',
        HeaderProductImg:'Prod_Img-',
        HeaderProductRoleText: `Pop-Tarts* S'mores Toaster Pastries`,
        HeaderProductTextOne: `Toasted, frozen, or straight from the box; add a little fun to your mornings with Pop-Tarts* S'mores toaster pastries.A delicious graham cracker flavoured crust stuffed with chocolatey marshmallow filling, frosted with rich chocolately icing. A chocolatey & fun way to awaken your senses at breakfast.`,
        HeaderProductTextTwo: 'Purchase This Product Online',
        Goback: true,
    },
    {
        HeaderProductLink: 'Rice Krispies Brand page',
        HeaderTextOne: 'Rice Krispies Squares* Bars',
        HeaderTextTwo: 'Our products',
        HeaderProductList: 'Rice Krispies Squares* Original Bars',
        HeaderProductImg:'RKSB Original 8ct 176g',
        HeaderProductRoleText: 'Rice Krispies Squares* Original Bars',
        HeaderProductTextOne: `Crispy rice cereal bars with ooey gooey marshmallow, Rice Krispies Squares* bars are sure to bring the fun to break time! Each chewy square is individually wrapped, perfect for lunchboxes for a mid-day snack, you can take them on the go for your kids activities, it's a sweet treat that is fun to eat.`,
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Rice Krispies Squares* Homestyle Original Bars',
        HeaderProductImg:'RKSB Homestyle Original',
        HeaderProductRoleText: 'Rice Krispies Squares* Homestyle Original Bars',
        HeaderProductTextOne: `Experience bigtime flavour and fun with our new Rice Krispies Squares* Homestyle Original bars that are 50% bigger than our 22 g Rice Krispies Squares* bars. We've taken our signature crispy rice and packed it with pockets of melted marshmallows throughout to craft our thickest, gooiest homestyle recipe.`,
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Rice Krispies Squares* Chocolate Chip Cookie Dough Flavour Bars',
        HeaderProductImg:'00064100147492_A1L1',
        HeaderProductRoleText: 'Rice Krispies Squares* Chocolate Chip Cookie Dough Flavour Bars',
        HeaderProductTextOne: `Crispy rice cereal bars with ooey gooey marshmallow, chocolatey chips and cookie dough flavour, Rice Krispies Squares* bars are sure to bring the fun to break time! Each chewy square is individually wrapped, perfect for lunchboxes for a mid-day snack or you can take them on the go for your kids’ activities. It's a sweet treat that is fun to eat`,
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Kellogg\'s® Rice Krispies',
        HeaderProductImg:'00064100148307_A1L1-1280x1280',
        HeaderProductRoleText: `Kellogg's® Rice Krispies Squares® Homestyle Chocolatey Chip Bars`,
        HeaderProductTextOne: `Experience big time flavour and fun with new Rice Krispies Squares® Homestyle Chocolatey Chip bars that are 50 % bigger than our 22 g Rice Krispies Squares* bar and packed with pockets of melted marshmallows throughout.`,
        HeaderProductTextTwo: 'Purchase This Product Online',
        Goback: true,
    },
    {
        HeaderProductLink: 'Special K Brand page',
        HeaderTextOne: 'Real Ingredients. Real',
        HeaderTextTwo: 'Our products',
        HeaderProductList: 'Special K* Blueberry Flavour',
        HeaderProductImg:'Prod_Img-',
        HeaderProductRoleText: 'Special K* Blueberry Flavour Fruit Crisps',
        HeaderProductTextOne: `Sweet meets sensible with Special K* Blueberry Flavour crisps. Delight in two light, crisp pastries with delicious berry taste, drizzled with a touch of icing for 100 calories per serving (25 g). They’re a win-win for your taste buds.`,
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Special K* Nuts & Grain Dark',
        HeaderProductImg:'00064100113312_A1L',
        HeaderProductRoleText: 'Special K* Strawberry Flavour Fruit Crisps',
        HeaderProductTextOne: `Sweet meets sensible with Special K* Strawberry Flavour fruit crisps. Delight in two light, crisp pastries with delicious berry taste, drizzled with a touch of icing for 100 calories per serving (25 g). They’re a win-win for your taste buds`,
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Special K* Nuts & Grain Cranberries & Almonds Bars',
        HeaderProductImg:'00064100113343_A1L1',
        HeaderProductRoleText: 'Special K* Nuts & Grain Cranberries & Almonds Bars',
        HeaderProductTextOne: `With sun-dried fruits, and roasted nuts, Special K* Nuts & Grain Cranberries & Almond bars are made with real, visible ingredients you can see and taste. Gluten-free with no artificial flavours or colours, each fruity, nutty bite proves it’s pure snack satisfaction.`,
        HeaderProductTextTwo: 'Purchase This Product Online',
    },
    {
        HeaderProductList: 'Special K* Nuts & Grain Cranberries & Almonds Bars',
        HeaderProductImg:'00064100113343_A1L1',
        HeaderProductRoleText: `Special K* Nuts & Grain Dark Chocolate Chunks & Almond Bars`,
        HeaderProductTextOne: `Sink your teeth into lightly roasted nuts and chunks of real dark chocolate, all folded into golden gluten-free rolled oats. Gluten-free Special K* Nuts & Grain Dark Chocolate Chunks & Almond bars are made with real, wholesome ingredients and no artificial flavours or colours for snacking satisfaction.`,
        HeaderProductTextTwo: 'Purchase This Product Online',
        Goback: true,
    }, 
]

export const HeaderWhereToBuy = [
    {
        HeaderLinks: 'Portable Snacks',
    },
    {
        HeaderLinks: 'Crackers',
    },
    {
        HeaderLinks: 'Chips',
    },
    {
        HeaderLinks: 'Waffles & Pancakes',
    },
];

export const whereToBuySoldByInputData = ['Zehrs','Instacart', 'Loblaws', 'Amazon', 'Fortinos', 'Independent City Market', 'Longos', 'No Frills', 'All Retailer'];

export const whereToBuyTellMeAboutInputData = ['Waffles & Pancakes','Chips', 'Crackers','All Products',];

export const whereToBuyRegionInputData = ['Yukon','Nova Scotia' ,'Newfoundland and Labrador','New Brunswick', 'Manitoba', 'British Columbia','Alberta','Prince Edward Island','Quebec', 'Ontario'];

export const cheezitMainpage = [
    {
        MainHeaderexact: 'Want it. Need it. Cheez-it.',
        MainImg: 'A shirtless man covered in',
        CarouselNextButton :'Carousel Next Slide',
    },
    {
        MainHeaderLink: 'Cheesy, Thin & Crispy',
        MainImgLocator: '.hero--alien-ufo-wrapper',
        CarouselNextButton :'Carousel Next Slide',  
        linkButton :'Check It Out',
    },
    {
        MainHeader: 'Cheesy, airy, puffy.',
        MainImg: 'Cheez-It Puffd White Cheddar',
        CarouselNextButton :'Carousel Next Slide',  
        linkButton :'Check It Out',
    },
];

export const cheezitDropdown = ['Shop our site', 'Original & Flavors',`Puff\'d`,`Snap\'d`, 'Grooves', 'Duoz', 'Snack Mix', 'Snack Packs'];

export const cheezitDropdownShop = ['SHOP ALL', 'Eat it', 'Wear It'];

export const headingpage = [
    {
        menuLink: 'Our Story',
    },
];

export const cheezitProductPage = [
    {
        mainpageHeader: 'Our Products' ,
        mainpageClick: 'Cheez-It crackers snack bowl',
        cardImg: 'Cheez-It Baked Snack Crackers',
        cardMainHeader: 'Cheesy, Crunchy, Satisfaction.',
        cardClick: 'Cheez-It® Original Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Original Snack',
        cardProductText: 'The one. The only. The',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        cardProductLink:'Where To Buy',
        cardProductWhereToBuyFirstImg:'Shop from other retailers',
        cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        cardProductLabel: 'Shop Cheez-It® Original Snack',
        cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Extra Toasty Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Extra Toasty Snack',
        cardProductText: 'You asked. We toasted. After',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Extra Toasty Cheddar Jack Snack Crackers',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Extra Toasty',
        cardProductText: 'Cheez-It® Extra Toasty Cheddar Jack perfectly combines the cheesy, marbled',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Extra Crunchy Bold',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Extra Crunchy Bold',
        cardProductText: 'Outrageously cheesy and',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Extra Cheesy Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Extra Cheesy Snack',
        cardProductText: 'We\'ve re-invented the wheel',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Extra Big Cheez-It® Snack',
        cardSectionImg: 'Baked Snack Crackers Extra',
        cardProductHeader: 'Extra Big Cheez-It® Snack',
        cardProductText: 'Cheez-It® Extra Big crackers',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® White Cheddar Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® White Cheddar Snack',
        cardProductText: 'They’re made with 100% real',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Pepper Jack Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Pepper Jack Snack',
        cardProductText: 'Not for the mild-mannered',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Cheddar Jack Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Cheddar Jack Snack',
        cardProductText: 'The cheesy, crunchy,',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Whole Grain Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Whole Grain Snack',
        cardProductText: 'Cheez-It® Whole Grain crackers are packed with whole grain goodness and 100%',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Italian Four Cheese',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Italian Four Cheese',
        cardProductText: 'We’re pretty good at what we',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Hot & Spicy Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Hot & Spicy Snack',
        cardProductText: 'Ready to spice up your snack',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Reduced Fat Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Reduced Fat Snack',
        cardProductText: 'At. Long. Last. Everything',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Buffalo Wing Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Buffalo Wing Snack',
        cardProductText: 'Make snack time more fun with',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Hidden Valley®',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Hidden Valley®',
        cardProductText: 'The Cheez-It® flavor you’ve',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Smoked Gouda Snack',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Smoked Gouda Snack',
        cardProductText: 'For the snacking adventurer,',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Smoked Cheddar',
        cardSectionImg: 'Baked Snack Crackers Cheez-It',
        cardProductHeader: 'Cheez-It® Smoked Cheddar',
        cardProductText: 'For the snacking adventurer,',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
        Goback: true,
    },
    {
        mainpageHeader: 'Our Products' ,
        mainpageClick: 'Snap\'d package with cheese',
        cardImg: 'Snap\'d texture',
        cardMainHeader: 'THIN AND CRISPY BAKED SNACKS',
        cardClick: 'Cheez-It® Snap\'d® Double',
        cardSectionImg: 'Snap\'d Cheez-It® Snap\'d®',
        cardProductHeader: 'Cheez-It® Snap\'d® Double',
        cardProductText: 'Thin, crispy, cheesy baked',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Snap\'d® Jalapeño',
        cardSectionImg: 'Snap\'d Cheez-It® Snap\'d®',
        cardProductHeader: 'Cheez-It® Snap\'d® Jalapeño',
        cardProductText: 'Cheez-It® Snap\'d® Jalapeño Jack Crackers are thin and crispy cheesy baked',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Snap\'d® Cheddar',
        cardSectionImg: 'Snap\'d Cheez-It® Snap\'d®',
        cardProductHeader: 'Cheez-It® Snap\'d® Cheddar',
        cardProductText: 'Cheez-It® Snap\'d® Cheddar Sour Cream & Onion Crackers are thin and crispy',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Snap\'d® Extra Crunchy Margherita Pizza Crackers',
        cardSectionImg: 'Snap\'d Cheez-It® Snap\'d®',
        cardProductHeader: 'Cheez-It® Snap\'d® Extra',
        cardProductText: 'With big cheese taste, Cheez-',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Snap\'d® Extra Crunchy Sharp White Cheddar Crackers',
        cardSectionImg: 'Snap\'d Cheez-It® Snap\'d®',
        cardProductHeader: 'Cheez-It® Snap\'d® Extra',
        cardProductText: 'Big cheese taste inside and',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
        Goback: true,
    },
    {
        mainpageHeader: 'Our Products' ,
        mainpageClick: 'Cheez-It Puff\'d package with',
        cardImg: 'Cheez-It Puff\'d in a bowl',
        cardMainHeader: 'AIRY AND PUFFY SNACKS BAKED',
        cardClick: 'Cheez-It® Puff\'d® Double',
        cardSectionImg: 'Puff\'d Cheez-It® Puff\'d®',
        cardProductHeader: 'Cheez-It® Puff\'d® Double',
        cardProductText: 'Taste the fun of puffy and',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Degerminated',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Puff\'d® White',
        cardSectionImg: 'Puff\'d Cheez-It® Puff\'d®',
        cardProductHeader: 'Cheez-It® Puff\'d® White',
        cardProductText: 'Up your snacking game with',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Degerminated',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Puff\'d® Cheddar',
        cardSectionImg: 'Puff\'d Cheez-It® Puff\'d®',
        cardProductHeader: 'Cheez-It® Puff\'d® Cheddar',
        cardProductText: 'Up your snacking game with',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Degerminated',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Puff\'d® Cheese',
        cardSectionImg: 'Puff\'d Cheez-It® Puff\'d®',
        cardProductHeader: 'Cheez-It® Puff\'d® Cheese',
        cardProductText: 'Ride the cheese wave of puffy',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Degerminated',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
        Goback: true,
    },
    {
        mainpageHeader: 'Our Products' ,
        mainpageClick: 'Cheez-It Grooves in a snack',
        cardImg: 'Cheez-It Grooves closeups',
        cardMainHeader: 'SO MUCH FLAVOR, IT\'S A MIND',
        cardClick: 'Cheez-It® Grooves® Bold',
        cardSectionImg: 'Grooves Cheez-It® Grooves®',
        cardProductHeader: 'Cheez-It® Grooves® Bold',
        cardProductText: 'Cheez-It® Grooves® Bold brings you deep flavor and deep crunch. We took the 100',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Grooves® Sharp',
        cardSectionImg: 'Grooves Cheez-It® Grooves®',
        cardProductHeader: 'Cheez-It® Grooves® Sharp',
        cardProductText: 'Cheez-It® Grooves® bring you',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Grooves® Zesty',
        cardSectionImg: 'Grooves Cheez-It® Grooves®',
        cardProductHeader: 'Cheez-It® Grooves® Zesty',
        cardProductText: 'Cheez-It® Grooves® brings you',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
        Goback: true,
    },
    {
        mainpageHeader: 'Our Products' ,
        mainpageClick: 'Duoz Box with crackers CHEEZ',
        cardImg: 'Cheez-It snack mix crackers',
        cardMainHeader: 'A MASH-UP OF EXCITING FLAVORS',
        cardClick: 'Cheez-It Duoz® Jalapeño &',
        cardSectionImg: 'Duoz Cheez-It Duoz® Jalapeño',
        cardProductHeader: 'Cheez-It Duoz® Jalapeño &',
        cardProductText: 'Every so often you need a',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It Duoz® Bacon &',
        cardSectionImg: 'Duoz Cheez-It Duoz® Bacon &',
        cardProductHeader: 'Cheez-It Duoz® Bacon &',
        cardProductText: 'Bacon and cheddar. It’s a',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
        Goback: true,
    },
    {
        mainpageHeader: 'Our Products' ,
        mainpageClick: 'Hands reaching for Cheez-It',
        cardImg: 'Cheez-It snack mix crackers',
        cardMainHeader: 'TASTE, TEXTURES AND FUN!',
        cardClick: 'Cheez-It® Snack Mix',
        cardSectionImg: 'Snack Mix Cheez-It® Snack Mix',
        cardProductHeader: 'Cheez-It® Snack Mix',
        cardProductText: 'A perfectly seasoned snack',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Cheese crackers (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Snack Mix Double',
        cardSectionImg: 'Snack Mix Cheez-It® Snack Mix',
        cardProductHeader: 'Cheez-It® Snack Mix Double',
        cardProductText: 'A perfectly seasoned snack mix of white cheddar crackers, Cheez-It® Original',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Cheese crackers (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
        Goback: true,
    },
    {
        mainpageHeader: 'Our Products' ,
        mainpageClick: 'Cheez-It Snack Packs variety',
        cardImg: 'Cheez-It snack mix crackers',
        cardMainHeader: 'ON-THE-GO SNACKING',
        cardClick: 'Cheez-It® Original Snack',
        cardSectionImg: 'Snack Packs Cheez-It®',
        cardProductHeader: 'Cheez-It® Original Snack',
        cardProductText: 'Cheesy, crunchy, satisfaction',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Cheese Lovers',
        cardSectionImg: 'Snack Packs Cheez-It® Cheese',
        cardProductHeader: 'Cheez-It® Cheese Lovers',
        cardProductText: 'Make snack time more fun with',
        // cardProductFirstHeader: 'Nutrition',
        // cardProductSecoundHeader: 'Ingredients',
        // cardProductFirstText:'Ingredients: Enriched flour (',
        // cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        // cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Extra Toasty Snack',
        cardSectionImg: 'Snack Packs Cheez-It® Extra',
        cardProductHeader: 'Cheez-It® Extra Toasty Snack',
        cardProductText: 'You asked. We toasted. After',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Snap\'d® Double Cheese Multi-Pack',
        cardSectionImg: 'Snack Packs Cheez-It® Snap\'d',
        cardProductHeader: 'Cheez-It® Snap\'d® Double',
        cardProductText: 'Thin, crispy, cheesy baked',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Enriched flour (',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Snap\'d® Snack',
        cardSectionImg: 'Snack Packs Cheez-It® Snap\'d',
        cardProductHeader: 'Cheez-It® Snap\'d® Snack',
        cardProductText: 'Packs of thin and crispy',
        // cardProductFirstHeader: 'Nutrition',
        // cardProductSecoundHeader: 'Ingredients',
        // cardProductFirstText:'Ingredients: Enriched flour (',
        // cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        // cardProductViewButton: 'View SmartLabel',
    }, 
    {
        cardClick: 'Cheez-It® Variety Snack Packs',
        cardSectionImg: 'Snack Packs Cheez-It® Variety',
        cardProductHeader: 'Cheez-It® Variety Snack Packs',
        cardProductText: 'With three flavors to choose',
        // cardProductFirstHeader: 'Nutrition',
        // cardProductSecoundHeader: 'Ingredients',
        // cardProductFirstText:'Ingredients: Enriched flour (',
        // cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        // cardProductViewButton: 'View SmartLabel',
    },
    {
        cardClick: 'Cheez-It® Snack Mix Snack Pack',
        cardSectionImg: 'Snack Packs Cheez-It® Snack',
        cardProductHeader: 'Cheez-It® Snack Mix Snack Pack',
        cardProductText: 'A perfectly seasoned snack',
        cardProductFirstHeader: 'Nutrition',
        cardProductSecoundHeader: 'Ingredients',
        cardProductFirstText:'Ingredients: Cheese crackers',
        cardProductSecoundText:'For full nutrition',
        // cardProductLink:'Where To Buy',
        // cardProductWhereToBuyFirstImg:'Shop from other retailers',
        // cardProductWhereToBuySecoundImg: 'Shop from other retailers',
        // cardProductLabel: 'Shop Cheez-It® Original Snack',
        // cardProductClose: 'Close the shop now shopping',
        cardProductViewButton: 'View SmartLabel',
        Goback: true,
    },
];

export const cheezitFooter = [
    {
        footerLinkExact: 'Shop All',
        Goback: true,
    },
    {
        footerLink: 'Home',
    },
    {
        footerLabelLink: 'Products',
        Goback: true,
    },
    {
        footerLinkExact: 'Where To Buy',
    },
    {
        footerLinkExact: 'Promotions',
        Goback: true,
    },
    {
        footerLink: 'Videos',
        Goback: true,
    },
    {
        footerLink: 'FAQ',
        Goback: true,
    },
    {
        footerLabelLink: 'Recipes',
        Goback: true,
    },
    {
        footerLabelLink: 'Cheez-It® Bowl',
        Goback: true,
    },
    {
        footerLink: 'Contact Us',
        Goback: true,
    },
    {
        footerLink: 'Site Map',
        Goback: true,
    },
    {
        footerLink: 'Facebook',
        closeTab: true,
    },
    {
        footerLink: 'Twitter',
        closeTab: true,
    },
    {
        footerLink: 'Instagram',
        closeTab: true,
    },
    {
        footerLink: 'YouTube',
        closeTab: true,
    },
    {
        footerLableText: 'Cookie Preferences',
        button: 'Reject All',
    },
    {
        footerLink: 'Shipping & Returns',
        Goback: true,
    },
    {
        footerLink: 'Privacy Notice',
        closeTab: true,
    },
    {
        footerLink: 'US Privacy',
        closeTab: true,
    },
    {
        footerLink: 'Terms of Use',
        closeTab: true,
    },
    {
        footerLink: 'Your Privacy Choices',
        closeTab: true,
    },
    {
        footerLink: 'Accessibility',
        closeTab: true,
    },
]

export const searchpage = [
    // {
    //     searchName: 'EGGO PANCAKES BUTTERM',
    //     searchNoData: 'No results for "EGGO PANCAKES',
    //     expectSearch:'Search Results',
    //     searchHeading: 'Results for "EGGO PANCAKES',
    //     searchLink:'EGGO PANCAKES BUTTERMILK',
    //     searchiImg:'Kellogg\'s® Eggo® Buttermilk',
    // },
    {
        searchName: 'Cheez-It® Baked Snack',
        searchNoData: 'No results found',
        searchHeading: 'Results for "Cheez-It® Baked',
        searchLink:'Cheez-It® Puff\'d® Cheese',
    },
]