export const kellanovamainpage = [
    {
        kellanovaheading: 'Welcome to Kellanova',
        kellanovaheading2: 'Check out our brands',
        kellanovaimg: 'Pringles, Club and Cheez IT',
    },
    {
        kellanovaLink: 'Our Brands',
        kellanovaimg: 'Packshots of Kellanova brands',
        kellanovaHeading:'Our Brands',
        kellanovaText:'Kellanova strives to provide',
    },
    {
        kellanovaLink: 'New Products',
    },
    {
        kellanovaLink: 'Special Offers',
    },
    {
        kellanovaLinkBuy: 'Where To Buy',
    },
    {
        kellanovaLinkUs: 'Contact Us',
    },
]

export const kellanvaImgs = [
         'cheez-it logo',
         'pringles logo',
         'club crackers logo',
         'RKT logo',
         'townhouse logo',
         'poptart logo',
         'rxbar logo',
         'moringstar farms logo',
         'eggo logo',
]

export const kellanovabody = [
    {
        kellanovaLink : 'Save Now',
        kellanovaimg: 'waffle',
        kellanovaHeading:'Coupons',
    },
    {
        kellanovaLink : 'View all products arrow',
        kellanovaimg: 'Packshots of Kellanova brands',
        kellanovaHeading:'Our Brands',
        kellanovaText:'Kellanova strives to provide',
    }
];

export const productDetails = [
    {
        headerName: 'Our Brands',
        productName: 'Austin',
        productHeader: 'Conveniently packaged to fit',
        productImg: 'Austin crackers',
        productHeader2: 'Big taste comes in small',
        productText:'Enjoy the big taste of Austin',
        productH2Text: 'Austin®',
        productText2: 'Kellanova brand products',
        productDetailLink: 'Austin Cheese Crackers with Cheddar Cheese Image Austin Cheese Crackers with',
        productDetailImg: 'Austin Cheese Crackers with',
        productDetailHeader: 'Austin Cheese Crackers with',
        productDetailText:'Sandwich Crackers, Cheese',
        productDetailReview: '2.0 out of 5 stars, average',
        goBack:true,
        // productDetailBuy:'click to see where to buy',
        // productDetailBuyHedaer: 'Shop Austin® Toasty Crackers',
        // productDetailclose: 'Close the shop now shopping',
        // productDetailNut: 'Nutrition',
        // productDetailIng: 'Ingredients',
        // productDeatilIngText: 'Ingredients: Enriched flour (',
        // productDetailTextFor:'For full nutrition',
        // productDetailButton: 'View SmartLabel',
        productNextText: 'More Favorites',
        productNextHeader:'Want it. Need it. Cheez-It®',
        productNextHeader2:'Endless flavors to #',
        productNextButton: 'View Brand',
    },
    {
        productDetailLink: 'Austin Toasty Crackers with',
        productDetailImg: 'Austin Toasty Crackers with',
        productDetailHeader: 'Austin Toasty Crackers with',
        productDetailText:'Baked peanut butter sandwich',
        productDetailReview: '2.2 out of 5 stars, average',
        productDetailBuy:'click to see where to buy',
        productDetailBuyHedaer: 'Shop Austin® Toasty Crackers',
        productDetailclose: 'Close the shop now shopping',
        productDetailNut: 'Nutrition',
        productDetailIng: 'Ingredients',
        productDeatilIngText: 'Ingredients: Enriched flour (',
        productDetailTextFor:'For full nutrition',
        productDetailButton: 'View SmartLabel',
        productNextText: 'More Favorites',
        productNextHeader:'Want it. Need it. Cheez-It®',
        productNextHeader2:'Endless flavors to #',
        productNextButton: 'View Brand',
    },
    {
        productDetailLink: 'Austin Cheese Crackers with Peanut Butter Image Austin Cheese Crackers with',
        productDetailImg: 'Austin Cheese Crackers with',
        productDetailHeader: 'Austin Cheese Crackers with',
        productDetailText:'Baked cheese and peanut',
        productDetailReview: '2.1 out of 5 stars, average',
        // productDetailBuy:'click to see where to buy',
        // productDetailBuyHedaer: 'Shop Austin® Toasty Crackers',
        // productDetailclose: 'Close the shop now shopping',
        productDetailNut: 'Nutrition',
        productDetailIng: 'Ingredients',
        productDeatilIngText: 'Ingredients: Enriched flour (',
        productDetailTextFor:'For full nutrition',
        productDetailButton: 'View SmartLabel',
        productNextText: 'More Favorites',
        productNextHeader:'Want it. Need it. Cheez-It®',
        productNextHeader2:'Endless flavors to #',
        productNextButton: 'View Brand',
    },
    {
        headerName: 'Our Brands',
        productName: 'Carr\'s',
        productHeaderLink: 'Carr’s®',
        productHeader: 'Since 1831, Carr\'s® Crackers',
        productImg: 'Carrs crackers',
        productHeader2: 'Everything is better with Carr’s®',
        productText:'Carr\'s® crackers are made',
        productH2Text: 'Carr\'s',
        productText2: 'Kellanova brand products',
        productDetailLink: 'Austin Cheese Crackers with Cheddar Cheese Image Austin Cheese Crackers with',
        productDetailImg: 'Austin Cheese Crackers with',
        productDetailHeader: 'Austin Cheese Crackers with',
        productDetailText:'Sandwich Crackers, Cheese',
        productDetailReview: '2.0 out of 5 stars, average',
        goBack:true,
        // productDetailBuy:'click to see where to buy',
        // productDetailBuyHedaer: 'Shop Austin® Toasty Crackers',
        // productDetailclose: 'Close the shop now shopping',
        // productDetailNut: 'Nutrition',
        // productDetailIng: 'Ingredients',
        // productDeatilIngText: 'Ingredients: Enriched flour (',
        // productDetailTextFor:'For full nutrition',
        // productDetailButton: 'View SmartLabel',
        productNextText: 'More Favorites',
        productNextHeader:'Want it. Need it. Cheez-It®',
        productNextHeader2:'Endless flavors to #',
        productNextButton: 'View Brand',
    },
]