export const productDetailsList = [
    {
        productMenuLabel: "Our Food",
        productImgCode: 'Town House Crackers closeup',
    },
    {
        productName: "CARR'S® TABLE WATER® CRACKED",
        productMenuLabel: "Recipes",
        productImgCode: 'Townhouse Crackers arranged',
        productId: '00059290575927'
    },
  ];

export const menuPageOurFood = [
    {
        productMenuLabel: "Our Food",
        productMenuImg:'Town House Crackers closeup',
        productMenuText:'Our Foods',
    },
    {
    ourFoodLink:'Kellogg’s* Town House* Original Crackers Image Kellogg’s* Town House* Original',
    ourFoodImg: "Kellogg’s* Town House*",
    ourFoodHeader:'Kellogg’s* Town House*',
   },
   {
    ourFoodLink:'Kellogg’s* Town House* FlipSides* Original Crackers Image Kellogg’s* Town House',
    ourFoodImg: "Kellogg’s* Town House*",
    ourFoodHeader:'Kellogg’s* Town House*',
   },
   {
    ourFoodLink:'Town House* Flatbread Crisps Italian Herb Crackers Image Town House* Flatbread',
    ourFoodImg: "Town House* Flatbread Crisps",
    ourFoodHeader:'Town House* Flatbread Crisps',
   },
   {
    ourFoodLink:'Town House* Flatbread Crisps Sea Salt & Olive Oil Crackers Image Town House*',
    ourFoodImg: "Town House* Flatbread Crisps Sea Salt & Olive Oil Crackers",
    ourFoodHeader:'Town House* Flatbread Crisps',
    ourFoodButton: 'click to see where to buy',
   },
   {
    ourFoodLink:'Town House* Pita Sea Salt',
    ourFoodImg: "Town House* Pita Sea Salt",
    ourFoodHeader:'Town House* Pita Sea Salt',
    ourFoodButton: 'click to see where to buy',
   },
   {
    ourFoodLink:'Town House* Pita Mediterranean Herb Crackers Image Town House* Pita',
    ourFoodImg: "Town House* Pita Mediterranean Herb Crackers",
    ourFoodHeader:'Town House* Pita',
    ourFoodButton: 'click to see where to buy',
   },
   {
    ourFoodTitleLink:'Buy Now at Wholesale Club',
    ourFoodLink: 'Kellogg’s* Town House* Original Crackers Image Kellogg’s* Town House* Original',
    ourFoodImgWholesale: "#site-layout",
    ourFoodHeaderWholesale:'#site-layout',
   },
   {
    ourFoodTitleLink:'Buy Now at Zehrs',
    ourFoodImgZehrs: "#site-layout",
    ourFoodHeaderZehrs:'#site-layout',
   },
   {
    ourFoodTitleLink:'Buy Now at Amazon',
    // ourFoodImg: "Town House Oven Baked",
    // ourFoodHeader:'Town House Oven Baked',
   },
   {
    ourFoodTitleLink:'Buy Now at Walmart',
    // ourFoodImg: "Town House Oven Baked",
    // ourFoodHeader:'Town House Oven Baked',
   },
   {
    ourFoodTitleLink:'Buy Now at Real Canadian',
    // ourFoodImg: "Town House Oven Baked",
    // ourFoodHeader:'Town House Oven Baked',
    ourFoodButtonLink:'Powered By Dotter',
   },
]

export const productMainPageList = [
    {
        productMenuLabel: "Our Food",
    },
    {
        productMenuLabel: "Recipes",
    },
    {
        productMenuLabel: "Sign Up",
    },
    {
        productMenuLabel: "Where To Buy",
    },
    {
        productMenuLabel: "Coupons",
    },
    {
        productMenuLink: "Français",
    },
    {
        productMenuLink: "English",
    },
  ];

export const productMainHeaderList = [
    {
        productCardList: "CRANBERRY AND PISTACHIO",
        productCardListImg: "CRANBERRY AND PISTACHIO",
        productCardListText: 'CRANBERRY AND PISTACHIO',
        PREPTIME: '20',
        TOTALTIME: '80',
        SERVINGS: '24',
        cardHeader: 'Directions',
        textFirst: '1. In small saucepan combine cranberries, white grape juice and honey. Bring to a simmer. Cook about 5 minutes or until cranberries are plump. Cool to room temperature.',
        textsecound: '2. In small mixing bowl beat',
        textThird: '3. Spoon cream cheese mixture',
        textNote: '*NOTE: Soften in microwave at',
        textLastNode: '**NOTE: To toast nuts spread',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '1/2 cup dried cranberries',
        IngredientsTextsecound:'Kellogg\'s® Town House® Original Crackers',
        IngredientsTextThird: '1/2 cup white grape juic',
        IngredientsTextFourth: '2 tablespoons honey',
        IngredientsTextFive: '1 package (225 g) cream cheese, softened*',
        IngredientsTextSix: '1/2 cup chopped pistachio nuts, toasted**',
        IngredientsTextSeven: '2 tablespoons chopped fresh parsley',
        IngredientsTextEight: '1/8 teaspoon salt',
        IngredientsTextNine: '1/8 teaspoon pepper',
    },
    {
        productCardList: "TOWN HOUSE FLIPSIDES APPLE,",
        productCardListImg: "TOWN HOUSE® FLIPSIDES ® APPLE",
        productCardListText: 'TOWN HOUSE® FLIPSIDES ® APPLE',
        PREPTIME: '10',
        TOTALTIME: '10',
        SERVINGS: '10',
        cardHeader: 'Directions',
        textFirst: '1. Spread cheese on crackers. Top with apple slices. Arrange on serving platter.',
        textsecound: '2. Sprinkle with walnuts and pomegranate seeds, if desired. Drizzle with honey.',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '170 g goat cheese, softened',
        IngredientsTextsecound:'30 Town House® Flipsides® Original Crackers',
        IngredientsTextThird: '1 medium apple, cored and thinly sliced',
        IngredientsTextFourth: '1⁄3 cup finely chopped walnuts',
        IngredientsTextFive: '3 tablespoons honey',
        IngredientsTextSix: 'Pomegranate seeds, optiona',
    },
    {
        productCardList: "CHOCOLATE DIPPED CRACKERS",
        productCardListImg: "CHOCOLATE DIPPED CRACKERS",
        productCardListText: 'CHOCOLATE DIPPED CRACKERS',
        PREPTIME: '10',
        TOTALTIME: '20',
        SERVINGS: '13',
        cardHeader: 'Directions',
        textFirst: '1. In small microwave-safe bowl microwave 85 g chocolate, uncovered, on high for 1 to 1 1/2 minutes or until melted, stirring every 15 seconds.',
        textsecound: `2. Dip Kellogg's® Town House® Pretzel FlipSides® Original crackers halfway into chocolate. Place on wax paper lined baking sheet. Scatter sprinkles over top (if desired). Let stand until set.`,
        textThird: '3. Melt additional chocolate. Drizzle over crackers (if desired). Let stand until set.',
        textNote: '*Note: To substitute milk chocolate or white chocolate for the semi-sweet, place 85 g chopped milk chocolate or white chocolate (or 1/2 cup morsels) in small microwave-safe bowl. Microwave, uncovered, at MEDIUM-HIGH (70% power) about 1 minute, stirring every 10 to 15 seconds.',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '85 g chopped, semi-sweet chocolate or 1/2 cup semi-sweet chocolate morsels*',
        IngredientsTextsecound:`39 Kellogg's® Town House® Pretzel FlipSides® Original crackers Multi-colored sprinkles`,
        IngredientsTextThird: 'Semi-sweet, milk or white chocolate',
    },
    {
        productCardList: "Chipotle Cheeseburger Sliders",
        productCardListImg: "Chipotle Cheeseburger Sliders",
        productCardListText: 'Chipotle Cheeseburger Sliders',
        PREPTIME: '20',
        TOTALTIME: '20',
        SERVINGS: '10',
        cardHeader: 'Directions',
        textFirst: '1. Spread mayonnaise on Kelloggs* Town House* Pretzel Flipsides* Original crackers. Set aside.',
        textsecound: '2. In medium bowl combine ground beef and seasoning. Use rounded tablespoonfuls to divide meat mixture into 20 portions. Form each portion into 2- x 1-inch oval. In 12-inch skillet cook burgers, uncovered, over medium-high heat for 5 minutes or until no longer pink, turning once. Remove from heat, keeping burgers in skillet. Top each with cheese piece. Cover and let stand for 1 to 2 minutes or until cheese melts.',
        textThird: '3. Top each cracker with burger and tomato slice.',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '3 tablespoons reduced-fat chipotle mayonnaise or mustard',
        IngredientsTextsecound:'Kelloggs* Town House* Pretzel Flipsides* Original crackers',
        IngredientsTextThird: '1 pound lean ground beef',
        IngredientsTextFourth: '2 teaspoons spicy Montreal steak seasoning blend',
        IngredientsTextFive: '5 slices cheddar cheese, cut into twenty 2- x 1-inch rectangles',
        IngredientsTextSix: '5 cherry tomatoes, thinly sliced',
    },
    {
        productCardList: "Cold Smoked Salmon Spread",
        productCardListImg: "Cold Smoked Salmon Spread",
        productCardListText: 'Cold Smoked Salmon Spread',
        PREPTIME: '10',
        TOTALTIME: '130',
        SERVINGS: '14',
        cardHeader: 'Directions',
        textFirst: '1. In small mixing bowl beat cream cheese on medium speed of electric mixer until fluffy. Add chives, lemon juice and dill. Beat until combined. Stir in salmon and capers.',
        textsecound: `2. Refrigerate at least 2 hours to blend flavors. Let stand at room temperature for 20 minutes. Garnish as desired. Serve with Kellogg's® Town House® Original Crackers.`,
        textNote: '*NOTE: Soften cream cheese in microwave at high for 15 to 20 seconds.',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '1 package (8 oz.) cream cheese, softened*',
        IngredientsTextsecound:'3 tablespoons chopped fresh chive',
        IngredientsTextThird: '1 tablespoon lemon juice',
        IngredientsTextFourth: '1 tablespoon chopped fresh dill',
        IngredientsTextFive: '4 ounces smoked salmon, flaked',
        IngredientsTextSix: '2 tablespoons capers',
        IngredientsTextSeven: `Kellogg's® Town House® Original Crackers`,
    },
    {
        productCardList: "Swiss Cheese and Grape Salsa",
        productCardListImg: "Swiss Cheese and Grape Salsa",
        productCardListText: 'Swiss Cheese and Grape Salsa',
        PREPTIME: '15',
        TOTALTIME: '15',
        SERVINGS: '32',
        cardHeader: 'Directions',
        textFirst: `1. In medium bowl toss together cheese, grapes, pecans, salad dressing and tarragon. Serve with Kellogg's® Town House® Flatbread Crisps - Italian Herb.`,
        textNote: '*NOTE: To toast pecans, spread evenly on baking sheet. Bake at 350°F for 5 to 10 minutes or until light golden brown, stirring once or twice.',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '2 cups finely shredded Swiss cheese',
        IngredientsTextsecound:'2 cups chopped green seedless grapes',
        IngredientsTextThird: '1/2 cup chopped pecans, toasted*',
        IngredientsTextFourth: '3 tablespoons honey mustard salad dressing',
        IngredientsTextFive: '2 tablespoons chopped fresh tarragon or basil',
        IngredientsTextSix: `Kellogg's® Town House® Flatbread Crisps - Italian Herb`,
    },
    {
        productCardList: "Mediterranean Dip",
        productCardListImg: "Mediterranean Dip",
        productCardListText: 'Mediterranean Dip',
        PREPTIME: '10',
        TOTALTIME: '10',
        SERVINGS: '16',
        cardHeader: 'Directions',
        textFirst: '1. In small bowl stir together feta cheese, olives, tomatoes and cream cheese.',
        textsecound: `2. Mound mixture on serving plate. Press basil around edges. Serve with Kellogg's® Town House® Original Crackers.`,
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '1 cup crumbled feta cheese',
        IngredientsTextsecound:'3/4 cup sliced pitted black olives, drained',
        IngredientsTextThird: '3/4 cup seeded and chopped tomatoes',
        IngredientsTextFourth: '1/2 cup soft cream cheese spread',
        IngredientsTextFive: '1/4 cup chopped fresh basil',
        IngredientsTextSix: `Kellogg's® Town House® Original Crackers`,
    },
    {
        productCardList: "Sun-Dried Tomato and Feta",
        productCardListImg: "Sun-Dried Tomato and Feta",
        productCardListText: 'Sun-Dried Tomato and Feta',
        PREPTIME: '10',
        TOTALTIME: '10',
        SERVINGS: '20',
        cardHeader: 'Directions',
        textFirst: '1. In medium bowl toss together cheese, sun-dried tomatoes and basil.',
        textsecound: `2. Carefully, stir in salad dressing. (If mixture seems dry, add additional salad dressing, 1 tablespoon at a time.) Serve with Kellogg's® Town House® Flatbread Crisps - Italian Herb.`,
        textNote: '*NOTE: Look for the oil-free, sun-dried tomato strips that still retain some moisture. Usually they come in bags. If you can only find the completely dried variety of sun-dried tomatoes, soak them in warm water for 30 minutes. Then, drain well and finely chop them before using in the recipe.',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '2 cups crumbled feta cheese (8 oz.)',
        IngredientsTextsecound:'1/2 cup julienne-cut sun-dried tomato strips* (oil free), finely chopped',
        IngredientsTextThird: '1/4 cup chopped fresh basil',
        IngredientsTextFourth: '1/3 cup Italian vinaigrette salad dressing',
        IngredientsTextFive: `Kellogg's® Town House® Flatbread Crisps - Italian Herb`,
    },
    {
        productCardList: "Party pizzas Party pizzas",
        productCardListImg: "Party Pizzas",
        productCardListText: 'Party Pizzas',
        PREPTIME: '15',
        TOTALTIME: '20',
        SERVINGS: '9',
        cardHeader: 'Directions',
        textFirst: `1. In small bowl stir together tomato paste, onion, water, oregano, basil, garlic powder and pepper. Spread on one side of each Kellogg's® Town House® Original Crackers, completely covering cracker. Arrange crackers, tomato side up, on baking sheet.`,
        textsecound: '2. Top with pepperoni slices. Sprinkle with cheese. Broil 4- to 5-inches from heat for 1 to 2 minutes or until cheese melts.',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '1/3 cup tomato paste',
        IngredientsTextsecound:'1 tablespoon finely chopped onion or sliced green onion',
        IngredientsTextThird: '1 1/2 teaspoons water',
        IngredientsTextFourth: '3/4 teaspoon dried oregano leaves',
        IngredientsTextFive: '1/4 teaspoon dried basil leaves',
        IngredientsTextSix: '1/8 teaspoon garlic powder',
        IngredientsTextSeven: 'Dash pepper',
        IngredientsTextEight: `Kellogg's® Town House® Original Crackers`,
        IngredientsTextNine: '18 slices pepperoni',
        IngredientsTextTen: '1/2 cup (2 oz.) shredded mozzarella cheese',
    },
    {
        productCardList: "Pub cheese dip Pub cheese dip",
        productCardListImg: "Pub Cheese Dip",
        productCardListText: 'Pub Cheese Dip',
        PREPTIME: '20',
        TOTALTIME: '20',
        SERVINGS: '',
        cardHeader: 'Directions',
        textFirst: '1. Place cheese in food processor bowl. Cover and pulse until cheese becomes crumbles. Add cream cheese, beer, mustard, paprika and garlic powder. Cover and process until smooth, stopping processor and scraping down sides of bowl as needed.',
        textsecound: '2. Serve cheese spread with Town House* FlipSides* Original crackers. (Store any leftover cheese spread, covered, in the refrigerator. Let stand at room temperature for 30 minutes before serving.)',
        textNote: 'Yield: 3 1/4 cups; 26 servings; (1 serving = 2 tablespoons plus 4 crackers)',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '1 pound Irish cheddar cheese, broken into chunks',
        IngredientsTextsecound:'4 ounces cream cheese',
        IngredientsTextThird: '1/2 cup lager beer or non-alcoholic beer',
        IngredientsTextFourth: '1 tablespoon spicy brown mustard',
        IngredientsTextFive: '1 teaspoon paprika',
        IngredientsTextSix: '1/4 teaspoon garlic powder',
        IngredientsTextSeven: 'Town House* FlipSides* Original crackers',
    },
    {
        productCardList: "Avocado and Mango Salsa",
        productCardListImg: "Avocado and Mango Salsa",
        productCardListText: 'Avocado and Mango Salsa',
        PREPTIME: '15',
        TOTALTIME: '',
        SERVINGS: '20',
        cardHeader: 'Directions',
        textFirst: '1. In small bowl toss together mango, avocado, onion, cilantro, lemon juice, jalapeño pepper (if desired), salt and pepper.',
        textsecound: '2. Spoon mango mixture on top of Kelloggs* Town House* Original Crackers. Serve immediately.',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '1 1/2 cups finely chopped mango or fresh pineapple',
        IngredientsTextsecound:'1 large avocado, halved, seeded, peeled, and finely chopped',
        IngredientsTextThird: '1 small onion, finely chopped',
        IngredientsTextFourth: '2 tablespoons chopped fresh cilantro',
        IngredientsTextFive: '1 tablespoon lemon juice or lime juice',
        IngredientsTextSix: '1 tablespoon finely chopped jalapeno pepper (optional)',
        IngredientsTextSeven: '1/8 teaspoon salt',
        IngredientsTextEight: '1/8 teaspoon pepper',
        IngredientsTextNine: 'Kelloggs* Town House* Original Crackers',
    },
    {
        productCardList: "Creamy Buffalo Chicken Dip",
        productCardListImg: "Creamy Buffalo Chicken Dip",
        productCardListText: 'Creamy Buffalo Chicken Dip',
        PREPTIME: '20',
        TOTALTIME: '20',
        SERVINGS: '32',
        cardHeader: 'Directions',
        textFirst: '1. Remove and discard chicken skin. Shred chicken into small pieces. (You should have about 3 cups.) Discard bones.',
        textsecound: '2. In large skillet combine chicken and hot sauce. Cook and stir over medium heat until heated through. Stir in cream cheese. Cook and stir until cheese is melted. Stir in salad dressing and blue cheese. Cook over medium heat until mixture is heated through, stirring frequently.',
        textThird: `3. Transfer to serving bowl*. Serve with celery and Kellogg's® Town House® Pretzel Flipsides® Original crackers.`,
        textNote: '*Note: For serving, mixture may be kept warm in 1-quart slow cooker on low heat.',
        cardHeaderTwo: 'Ingredients',
        IngredientsTextFirst: '1 (about 2 lbs.) rotisserie-roasted, savory chicken',
        IngredientsTextsecound:'1/2 to 3/4 cup hot pepper sauce',
        IngredientsTextThird: '1 package (8 oz.) reduced-fat cream cheese, cut up',
        IngredientsTextFourth: '1 cup ranch salad dressing',
        IngredientsTextFive: '1/2 cup crumbled blue cheese (2 oz.)',
        IngredientsTextSix: 'Celery sticks',
        IngredientsTextSeven: `Kellogg's® Town House® Pretzel Flipsides® Original crackers`,
        IngredientsTextEight: `Kellogg's® Town House® Original Crackers`,
    },
    // {
    //     cardHeader: 'Directions',
    //     textFirst: '1. In small saucepan combine',
    //     textsecound: '2. In small mixing bowl beat',
    //     textThird: '3. Spoon cream cheese mixture',
    //     textNote: '*NOTE: Soften in microwave at',
    //     textLastNode: '**NOTE: To toast nuts spread',
    // },
    // {
    //     cardHeader: 'Directions',
    //     textFirst: '/2 cup dried cranberries',
    //     textsecound:'Kellogg\'s® Town House®',
    //     textThird: '/2 cup white grape juice',
    //     textFourth: 'tablespoons honey',
    //     textFive: '1 package (225 g) cream',
    //     textSix: '1/2 cup chopped pistachio',
    //     textSeven: 'tablespoons chopped fresh parsley',
    //     textEight: '/8 teaspoon salt',
    //     textNine: '/8 teaspoon pepper',
    // },
  ];

export const productFooterList = [
    {
        footerLabels: "Home",
    },
    {
        footerLable: "Sign Up",
        footerCheckText: 'SIGN UP TO FIND OUT ABOUT NEW',
    },
    {
        footerLable: "Coupons",
        footerCheckText:'Coupons'
    },
    {
        footerLable: "Our Food",
        footerCheckImg:'Town House Crackers closeup'
    },
    {
        footerLabels: "Contact Us",
        footerCheckText:'Contact Us by Email'
    },
    {
        footerLableLink: "Cookie Preferences",
        footerCheckButton:'Reject All'
    },
    {
        footerLableLink: "Privacy Notice",
        footerCheckText:'Kellanova Logo_brand logo'
    },
    {
        footerLableLink: "Terms of Use",
        footerCheckText:'Kellanova Logo'
    },
    {
        footerLableLink: "Accessibility",
        footerCheckText:'Kellanova Logo'
    },
    {
        footerTop: "back to top",
    },
  ];

export const appCreate = {
    firstName: "Mathu",
    LastName: "ravanan",
    Email: "Mono@gmail.com",
    confirmEmail: "Mono@gmail.com",
    DOB: "2024-01-01",
    approver: false,
  };

export const buyRegionButton = [
     "Manitoba",
     "Alberta",
    "Ontario",
];

export const buySoldByButton = [
     "Real Canadian Superstore",
     "Instacart",
     "Metro Ontario",
    'All Retailer',
];

export const cardListButton = [
    {
        header: 'Sign Up Now!',
        text: 'Sign up now to get our latest',
        clickLink: 'Join Today',
        expectHeader: 'SIGN UP TO FIND OUT ABOUT NEW'
    },
    {
        header: 'Where to Buy',
        text: 'Running low on Town House*',
        clickLink: 'Shop Now',
        expectHeader: 'Where To Buy'
    },
]